# Generated by Django 4.2.9 on 2024-03-18 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('pontos', models.CharField(max_length=50)),
                ('detalhes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('hamburguer', 'Hambúrguer'), ('sorvete', 'Sorvete'), ('porcao', 'Porção')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Pratos',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto'),
        ),
    ]
