# Generated by Django 4.2.9 on 2024-03-19 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_carrinho_produto_delete_atividade_delete_pratos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho_lanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=50, verbose_name='número')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('pontos', models.CharField(max_length=50)),
                ('detalhes', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Produto',
            new_name='Produto_lanche',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.AddField(
            model_name='carrinho_lanche',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto_lanche'),
        ),
    ]
