# Generated by Django 4.2.9 on 2024-03-19 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_carrinho_lanche_rename_produto_produto_lanche_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField(max_length=50, verbose_name='número')),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('hamburguer', 'Hambúrguer'), ('sorvete', 'Sorvete'), ('porcao', 'Porção')], max_length=50)),
                ('Preco', models.CharField(max_length=100)),
                ('form', models.CharField(choices=[('cartao', 'Cartão de Crédito'), ('cartao', 'Cartão de Débito'), ('pix', 'Pix')], max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Produto_lanche',
            new_name='Produtos',
        ),
        migrations.DeleteModel(
            name='Carrinho_lanche',
        ),
        migrations.AddField(
            model_name='carrinhos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produtos'),
        ),
    ]
