# Generated by Django 4.2.9 on 2024-03-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_carrinhos_rename_produto_lanche_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhos',
            name='qtde',
            field=models.IntegerField(max_length=50, verbose_name='qtde'),
        ),
    ]
