# Generated by Django 4.2.9 on 2024-03-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_carrinhos_qtde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinhos',
            name='Preco',
        ),
    ]
